### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by leonlan** [JoostBerkhout/PyKDA#1]
Hé @JoostBerkhout, ik dacht het is wel zo makkelijk om feedback op Github te doen - dan kan ik ook refereren naar code en kunnen we dit interactiever bespreken.

## Docs 
- Leuk logo! Logo kun je het best vervangen van JPG naar PNG. JPG kan geen transparante achtergronden hebben, maar PNG wel. Zodat je geen white background hebt in dark mode
- Je kunt overwegen om een `CITATION.cff` file toe te voegen aan je repository. Zie https://github.com/N-Wouda/ALNS/blob/master/CITATION.cff. Dan krijg je citation data in de sidebar.
- Je kunt ook je examples renderen in je documentatie en tegelijkertijd beschikbaar maken in colab.
  - https://github.com/danielfrg/mkdocs-jupyter : dit is een package om je notebooks te renderen in mkdocs.
  - Hier moet je even voor googlen maar je kunt volgens mij heel makkelijk een Colab link maken door deze string te formatten naar jouw eigen situatie: https://colab.research.google.com/github/username/repository/blob/master/notebook.ipynb
  Die blijft dan ook altijd up-to-date met veranderingen op je Github.
  - Om je notebook lokaal en op Colab te runnen heb je een beetje extra boilerplate nodig, zie voorbeeld van Alessandro's boek: https://colab.research.google.com/github/mobook/MO-book/blob/main/notebooks/02/03-mad-portfolio-optimization.ipynb#scrollTo=5ssUqKOaPVaE In het eerste code block wordt gecheckt of je in een colab environment zit, en zoja, dan pip install je de package. Lokaal wordt dit genegeerd.

## Code
- Style:
  - Ik zou `Markov_chain.py` veranderen naar `MarkovChain.py` or `markov_chain.py`. Eerste is PascalCase' stijl en tweede is Python stijl. De huidige file name zit er tussenin en valt buiten de conventies.
- Typing: 
    - `np.ndarray or list[list] or str` -> `Union[np.ndarray, list[list], str]` of je kunt `|` gebruiken
	    - https://github.com/JoostBerkhout/PyKDA/blob/166c6e4535e1eb70cc3565fef97f2639fb8cd410/pykda/Markov_chain.py#L30
    - Vanaf Python 3.9 kun je `list` gebruiken in plaats van `typing.List`.  Zelfde met `dict` en `tuple`.
	    - https://github.com/JoostBerkhout/PyKDA/blob/166c6e4535e1eb70cc3565fef97f2639fb8cd410/pykda/Markov_chain.py#L7
    - `-> None` output kun je weglaten, dat is namelijk impliciet
	    - https://github.com/JoostBerkhout/PyKDA/blob/166c6e4535e1eb70cc3565fef97f2639fb8cd410/pykda/Markov_chain.py#L37
- Features
    - Heb je `cached_property` _echt_ nodig op je MarkovChain class? Ik ken je algoritme niet dus ik weet niet hoe vaak bepaalde properties worden aangeroepen. Maar `MarkovChain` heeft veel internal state en lijkt redelijk vaak te updaten. `cached_property` cachet een property, maar als je interne variabelen veranderen, dan wordt dit dus niet meer geupdated. Een robustere design keuze is om niet te cachen en om `property` te gebruiken. 
	    - https://github.com/JoostBerkhout/PyKDA/blob/166c6e4535e1eb70cc3565fef97f2639fb8cd410/pykda/Markov_chain.py#L65
    - `normalizer` argument wordt niet gebruikt in `load_predefined_transition_matrix`
        - In `normalizer.py` kun je `normalizer_type = Callable[[np.ndarray], np.ndarray]` het best bovenaan zetten (is meteen duidelijk) en hebt best met `_` prefix odat je daarmee niet perongeluk user variables overschrijft. Dus `_normalizer_type`.
        - https://github.com/JoostBerkhout/PyKDA/blob/166c6e4535e1eb70cc3565fef97f2639fb8cd410/pykda/normalizers.py#L95
    - Het `KDA` algoritme neemt nu als input een markov chain en slaat deze op, en past dit telkens aan als je `run` aanroept. Een robuustere interface is als volgt: je slaat de MC chain niet op, maar geeft dit mee als argument in `run`. Als output krijg je je nieuwe MC terug. Hetzelfde kun je doen met `cut_edges`. 
	    - https://github.com/JoostBerkhout/PyKDA/blob/166c6e4535e1eb70cc3565fef97f2639fb8cd410/pykda/KDA.py#L43

**Comment by JoostBerkhout** [comment]
Feedback from Alessandro: write out how to pronounce PyKDA :-).

**Comment by JoostBerkhout** [comment]
Dank @leonlan ! Ik heb alles verwerkt op de volgende punten na:

- Ik had [mkdocs-jupyter](https://github.com/danielfrg/mkdocs-jupyter) geprobeerd (al eerder). Echter laadt die de interactieve netwerk plots niet. De plotting environment van pyvis lijkt niet breed toepasbaar. Om niet teveel werk ervan te hebben, had ik er maar voor gekozen om gewoon te linken naar Google Colab notebooks.
- Ik link nu naar de Google Colab notebooks vanuit mijn Google Drive. Dus als ik die nu aanpas, dan wordt dat ook automatisch geupdatet in git(hub). Volgens mij heeft dat dezelfde voordelen als die jij schetst.
- Ik heb ervoor gekozen om de de "extra boilerplate" niet te gebruiken maar gewoon een opmerking geplaatst dat als `pykda` al geinstalleerd is, je de betreffende stap kunt overslaan.
- Ik worstelde al met de `Markov_chain.py` naamgeving :-). Aan de ene kant wil ik de naam-hoofdletter in ere houden (zeker van iemand zoals Markov), maar ook aan de Python style te voldoen. Dan neig ik eerder naar `markov_chain.py` of toch `Markov_chain.py`. Wat jij? (idem trouwens voor `MarkovChain.P`, gangbaar in de literatuur is om een transitie matrix met een hoofdletter p aan te duiden)
- Is `from typing import Callable` ook overbodig in Python >=3.9 via een andere manier?
- Wat is er robuust aan als de gegeven Markov chain aan KDA in-place verandert (zelf vind ik dat juist minder robuust)? Zou het een optie zijn om het optioneel te maken?

**Comment by leonlan** [comment]
> Ik worstelde al met de Markov_chain.py naamgeving :-). Aan de ene kant wil ik de naam-hoofdletter in ere houden (zeker van iemand zoals Markov), maar ook aan de Python style te voldoen. Dan neig ik eerder naar markov_chain.py of toch Markov_chain.py. Wat jij? (idem trouwens voor MarkovChain.P, gangbaar in de literatuur is om een transitie matrix met een hoofdletter p aan te duiden)

Dit is puur een kwestie van smaak. Ik ben fan van class name als file name, dus `MarkovChain.py`. Maar Python standaard is `markov_chain.py` of zelfs soms `markovchain.py`. De huidige benaming is niet verkeerd, naming conventions breken over het algemeen geen functionaliteit ;-)


> Is from typing import Callable ook overbodig in Python >=3.9 via een andere manier?

Nee `Callable` heb je nog steeds nodig. Je kunt alleen generics zoals `list`, `dict`, `set` en `tuple` gebruiken.

> Wat is er robuust aan als de gegeven Markov chain aan KDA in-place verandert (zelf vind ik dat juist minder robuust)? Zou het een optie zijn om het optioneel te maken?

Dit heb ik verkeerd uitgelegd. Wat ik bedoelde is dat `KDA.run` de Markov chain als input neemt maar niet in-place aanpast. Het moet een nieuw Markov chain object terug geven, terwijl de input Markov chain onaangepast blijft. `KDA` hoeft dan ook geen Markov chain op te slaan; KDA hoeft niet de verantwoordelijkheid te hebben om een Markov chain te bewaren om te werken.

**Comment by JoostBerkhout** [comment]
@leonlan: ik maak een kopie van de originele MarkovChain die aan KDA wordt gegeven. De MarkovChain die in KDA wordt opgeslagen is de "huidige versie" van MarkovChain n.a.v. KDA wijzigingen.

**Comment by leonlan** [comment]
Hier is mijn suggestie over `KDA` beter uitgewerkt!

In je huidige code in (`KDA.py`) heb je dit:

```python
MC = MarkovChain("Courtois_matrix")
kda = KDA(
    original_MC=MC, CO_A="CO_A_1(1)", CO_B="CO_B_3(0)", symmetric_cut=False
)
kda.run()
kda.plot(file_name="Courtois_matrix_after_KDA_1_0")

```

Het maken van een kopie is goed (`original_MC` wordt als kopie opgeslagen), maar het is in principe niet eens nodig om de Markov chain op te slaan, omdat KDA maar 1x gerund wordt als ik het goed begrijp. Het is beter om dingen zo expliciet mogelijk te maken: hoe weet ik bijvoorbeeld als user dat `kda.run()` nu de Markov chain aanpast? En waarom moet KDA de Markov chain opslaan als deel van zijn state?

Je zou het bijvoorbeeld ook zo kunnen doen denk ik:

```python
MC_in = MarkovChain("Courtois_matrix")
kda = KDA(CO_A="CO_A_1(1)", CO_B="CO_B_3(0)", symmetric_cut=False)
MC = kda.run(MC_in)
MC.plot(file_name="Courtois_matrix_after_KDA_1_0")

```

`KDA` als class is hierdoor beter te begrijpen: het is een algoritme dat je initialiseert met bepaalde condities en eigenschappen. Met `KDA.run` pas je het algoritme toe op een Markov chain. De verwachting is dat je input niet wordt aangepast en dat de return value de nieuwe Markov chain is. Een ander voordeel is dat KDA hierdoor geen plot functions nodig heeft. Dat is mooi, want KDA (als algoritme) hoort immers ook niet te plotten. Zie ook https://en.wikipedia.org/wiki/Single_responsibility_principle. GPT legt het denk ik iets beter uit:

>	The Single Responsibility Principle (SRP) is a computer programming principle that's part of the five principles of SOLID. The principle states that every module, class, or function in a program should have responsibility over a single part of that software's functionality. Each responsibility should be entirely encapsulated by the class. 
>
> It's all about cohesion in software design — the idea that an object, method or module should have only one reason to change.
>
> The benefits of adhering to the SRP are numerous, but the most important advantage is that it makes software design more modular and thus easier to understand, modify, and test. By limiting each class to a single responsibility, it ensures that the class is written with minimal dependencies on other classes, which in turn makes the code more robust and less prone to bugs.

**Comment by JoostBerkhout** [comment]
Dank voor de reflectie @leonlan. Als je KDA toepast, wil ik ook de MarkovChains opslaan die die along the way vindt. Dus ook de initiele MarkovChain wil ik opslaan. Zodoende kun je achteraf bestuderen wat de evolutie van MarkovChains is geweest in KDA (zie ook KDA.log). Ook kun je in principe KDA meermaals achter elkaar runnen. Elke run voegt dan zijn gevonden MarkovChains toe aan KDA.log. Hoe zou jij dit modelleren vanuit SRP gedachte?

**Comment by leonlan** [comment]
De huidige `KDA.log` implementatie is prima. Om het nog meer modulair/SRP te maken kun je er een `Logger` of `Statistics` class voor maken die deze gegevens opslaat. Het is feature-wise niet anders dan wat je nu het, maar het is dan wel explicitier.

Je kunt nog steeds alle Markov chains opslaan die je along-the-way vindt. Het verschil zit vooral in de methods die je nu hebt geimplemnteerd: deze nemen aan dat er een `self.MC` variable aka de huidige MC. Hier is een voorbeeld van hoe ik het zou doen (code werkt niet, puur ter illustratie):

<details>
<summary>Example</summary>


```python

"""
Contains the Kemeny Decomposition Algorithm (KDA) class.
"""
import numpy as np

from pykda.Markov_chain import MarkovChain
from pykda.loaders import load_transition_matrix
from pykda.normalizers import _normalizer_type, standard_row_normalization


class Statistics:
    """
    Collects statistics about about the KDA algorithm.
    """

    def __init__(self):
        self.iterations = 0
        self.edges_cut = []
        self.markov_chains = []

    def collect(self, edges_cut, markov_chain):
        """
        Collects statistics about the KDA algorithm.
        """
        self.iterations += 1
        self.edges_cut.append(edges_cut)
        self.markov_chains.append(markov_chain)


class KDA:
    """
    Kemeny Decomposition Algorithm (KDA) class.

    KDA will iteratively cut 'edges' to decompose an original Markov chain (MC).
    An edge corresponds to a MC transition probability. The notation of Berkhout
    and Heidergott (2019) is used.

    Attributes
    ----------
    MC : MarkovChain
        Current Markov chain during KDA.
    log : dict
        Dictionary which logs the edges cut by KDA during the iterations. It
        also logs the Markov chains after each iteration. Each iteration of
        the inner-loop is stored by appending the list log['edges cut']. It is
        initialized with [None] to make the indexing easier. The Markov chains
        are stored in log['Markov chains'], where the original/initial MC is
        stored at index 0.

    Methods
    -------
    run()
        This will run KDA.
    cut_edges(*args)
        Allows one to cut manual edges in the current Markov chain to create
        a new Markov chain after normalization

    """

    def __init__(
        self,
        CO_A: str = "CO_A_1(1)",
        CO_B: str = "CO_B_3(0)",
        symmetric_cut: bool = False,
        verbose: bool = False,
        normalizer: _normalizer_type = standard_row_normalization,
    ):
        """
        Parameters
        ----------
        original_MC : MarkovChain
            Original Markov chain object to which KDA will be applied.
        CO_A : str
            Condition of how often the Kemeny constant derivatives are being
            recalculated (outer while loop in KDA). The options are:

                - 'CO_A_1(i)' = Number of times performed < i
                - 'CO_A_2(E)' = Number of ergodic classes in current MC is < E
                - 'CO_A_3(C)' = Number of strongly connected components in
                                current MC is < C
        CO_B : str
            Condition of how many edges are being cut per iteration (inner while
            loop in KDA). The options are:

                - 'CO_B_1(e)' = Number of edges cut is < e
                - 'CO_B_2(E)' = Number of ergodic classes in MC is < E
                - 'CO_B_3(q)' = Not all edges with MC.KDer < q are cut
        symmetric_cut : bool
            If True, cutting (i, j) will also cut (j, i). If False, only (i, j).
        verbose : bool
            If true, information will be printed, else not.
        normalizer : normalizer_type
            Normalizer used to create a stochastic matrix from a matrix.
        """

        self.statistics = Statistics()
        self.CO_A = CO_A
        self.CO_A_type = CO_A[:6]
        self.num_in_CO_A = self.get_num_in_str_brackets(CO_A)
        self.CO_B = CO_B
        self.CO_B_type = CO_B[:6]
        self.num_in_CO_B = self.get_num_in_str_brackets(CO_B)
        self.symmetric_cut = symmetric_cut
        self.normalizer = normalizer
        self.verbose = verbose

    @staticmethod
    def get_num_in_str_brackets(s):
        """Returns the number given between brackets in string s."""

        return int(s[s.find("(") + 1 : s.find(")")])

    def condition_A(self, MC: MarkovChain) -> bool:
        """Returns whether condition A is True or False."""

        if self.CO_A_type == "CO_A_1":
            return self.iterations_count < self.num_in_CO_A

        if self.CO_A_type == "CO_A_2":
            return MC.num_ergodic_classes < self.num_in_CO_A

        if self.CO_A_type == "CO_A_3":
            return MC.num_strongly_connected_components < self.num_in_CO_A

        raise Exception("Unknown condition A chosen (CO_A).")

    def condition_B(self, MC: MarkovChain) -> bool:
        """Returns whether condition B is True or False."""

        if self.CO_B_type == "CO_B_2":
            return MC.num_ergodic_classes < self.num_in_CO_B

        raise Exception("Unknown condition B chosen (CO_B).")

    def run(self, init: MarkovChain) -> MarkovChain:
        """Runs KDA with conditions CO_A and CO_B."""

        self.iterations_count = 0  # of the outer while loop of KDA
        self.statistics.collect([], init)

        MC = init

        # start cutting till condition A fails
        while self.condition_A(MC):
            MC = self.cut_till_condition_B_fails(MC)
            self.iterations_count += 1

        return MC

    def cut_till_condition_B_fails(self, MC: MarkovChain) -> MarkovChain:
        """Cuts edges till condition B fails."""

        if self.CO_B_type == "CO_B_1":
            edges = MC.most_connecting_edges(self.num_in_CO_B)
            return self.cut_edges(MC, *edges)

        elif self.CO_B_type == "CO_B_2":
            row_indexes, col_indexes = MC.sorted_edges()
            num_cut = 0

            while self.condition_B(MC):  # inner while loop
                MC = self.cut_edges(
                    MC,
                    row_indexes[num_cut : num_cut + 1],
                    col_indexes[num_cut : num_cut + 1],
                )
                num_cut += 1

            return MC

        elif self.CO_B_type == "CO_B_3":
            edges = MC.edges_below_threshold(self.num_in_CO_B)
            return self.cut_edges(MC, *edges)

        else:
            raise Exception("Unknown condition B chosen (CO_B).")

    def cut_edges(self, MC: MarkovChain, *args) -> MarkovChain:
        """Cut given edges in the Markov chain and normalize afterward.

        There are different options to specify which edges to cut via args.
        When self.symmetric_cut = True, also the reversed edges are cut.

        Parameters
        ----------
        args :
            There are three options for args:
                1. One tuple of length 2 indicating which edge to cut.
                2. One list of tuples of edges which to cut.
                3. Two lists or np.ndarrays indicating which edges to cut.

        """

        if len(args) == 1:
            if isinstance(args[0], tuple):
                return self._cut_edges(MC, [args[0][0]], [args[0][1]])
            elif isinstance(args[0], list):
                assert all(isinstance(x, tuple) for x in args[0])
                row_indexes, col_indexes = map(list, zip(*args[0]))
                return self._cut_edges(MC, row_indexes, col_indexes)
            else:
                raise Exception(
                    "Expected list of tuples or tuple in case "
                    "one argument is given in KDA.cut_edges()."
                )
        elif len(args) == 2:
            return self._cut_edges(MC, args[0], args[1])
        else:
            raise Exception("Expected 1 or 2 arguments in KDA.cut_edges().")

    def _cut_edges(
        self,
        MC: MarkovChain,
        row_indexes: np.ndarray | list,
        col_indexes: np.ndarray | list,
    ) -> MarkovChain:
        """Cut given edges in the Markov chain and normalize afterward.

        When self.symmetric_cut = True, also the reversed edges are cut.

        Parameters
        ----------
        row_indexes : np.ndarray | list
            Row indexes of the edges to be cut.
        col_indexes : np.ndarray | list
            Columns indexes of the edges to be cut.

        """

        if self.symmetric_cut:
            row_indexes, col_indexes = np.concatenate(
                (row_indexes, col_indexes)
            ), np.concatenate((col_indexes, row_indexes))

        MC.P[row_indexes, col_indexes] = 0  # cut edges
        new_P = load_transition_matrix(MC.P, self.normalizer)
        MC = MarkovChain(new_P)

        # Log data about the edges that have been cut.
        edges = [(x, y) for x, y in zip(row_indexes, col_indexes)]
        self.statistics.collect(edges, MC)

        self.check_for_infinite_loops()

        return MC

    def report(self):  # pragma: no cover
        """Prints a report of KDA."""

        # init
        edges_cut = self.statistics.edges_cut
        MCs = self.statistics.markov_chains

        print("\nKDA report:")
        print("===========\n")

        print("KDA settings:")
        print(f"- Condition A: {self.CO_A} ({self.condition_A_translator()})")
        print(f"- Condition B: {self.CO_B} ({self.condition_B_translator()})")
        print(f"- Symmetric cut: {self.symmetric_cut}\n")

        print("Initial Markov chain (MC) is:")
        print(f"{MCs[0]}\n")

        print("KDA progress is:")
        for iteration_num, (edges_cut, MC) in enumerate(zip(edges_cut, MCs)):
            print(f"* Iteration {iteration_num}:")
            print(f"   - Edges cut: {edges_cut}")
            print(f"   - Ergodic classes: {MC.ergodic_classes}")
            print(f"   - Transient classes: {MC.transient_classes}")
            scc = MC.strongly_connected_components
            print(f"   - Strongly connected components: {scc}")
            wcc = MC.weakly_connected_components
            print(f"   - Weakly connected components: {wcc}")

    def check_for_infinite_loops(self):
        """Due to fixes for normalization, it may happen that the same edge is
        cut over and over again. This check raises an error in that case.
        """

        if len(self.statistics.edges_cut) > 2:
            edges_cut_now = set(self.statistics.edges_cut[-1])
            edges_cut_prev = set(self.statistics.edges_cut[-2])
            edges_cut_prev2 = set(self.statistics.edges_cut[-3])
            same_edges_cut = edges_cut_now & edges_cut_prev & edges_cut_prev2
            if len(same_edges_cut) > 0:
                raise Warning(
                    "Possible infinite KDA loop detected: the following edges "
                    f"may be cut over and over again: {same_edges_cut}. "
                    f"If you see this message more than two times, try using"
                    f" another KDA setting that cuts less edges to avoid this."
                )

    @staticmethod
    def get_num_in_brackets(s):
        """Gets the number given between brackets in string s."""

        return int(s[s.find("(") + 1 : s.find(")")])

    def condition_A_translator(self):  # pragma: no cover
        """Translates the condition A into something readable."""

        if self.CO_A_type == "CO_A_1":
            return f"continue till {self.num_in_CO_A} times performed"

        if self.CO_A_type == "CO_A_2":
            return f"continue till # ergodic classes is {self.num_in_CO_A}"

        if self.CO_A_type == "CO_A_3":
            return (
                f"continue till # strongly connected components "
                f"{self.num_in_CO_A}"
            )

        raise Exception("Unknown condition A chosen (CO_A).")

    def condition_B_translator(self):  # pragma: no cover
        """Translates the condition B into something readable."""

        if self.CO_B_type == "CO_B_1":
            return f"continue till {self.num_in_CO_B} edge(s) cut"

        if self.CO_B_type == "CO_B_2":
            return f"continue till # ergodic classes is {self.num_in_CO_B}"

        if self.CO_B_type == "CO_B_3":
            return (
                f"continue till all edges with Kemeny constant derivative"
                f" < {self.num_in_CO_B} are cut"
            )

        raise Exception("Unknown condition B chosen (CO_B).")

    def plot_progress(self, **kwargs):  # pragma: no cover
        """Plots the Markov chains in the log. The kwargs are passed to the
        plot method of the Markov chain. Refer to MarkovChain.plot() for more
        details."""

        for i, MC in enumerate(self.log["Markov chains"]):
            MC.plot(**kwargs)

    def plot(self, **kwargs):  # pragma: no cover
        """Plots the Markov chain after KDA. Refer to MarkovChain.plot() for
        more details."""

        self.MC.plot(**kwargs)


if __name__ == "__main__":  # pragma: no cover
    MC_in = MarkovChain("Courtois_matrix")
    kda = KDA(CO_A="CO_A_1(1)", CO_B="CO_B_3(0)", symmetric_cut=False)
    MC_out = kda.run(MC_in)
    MC_out.plot(file_name="Courtois_matrix_after_KDA_1_0")

    # This contains all markov chains found along-the-way.
    kda.statistics.markov_chains
    kda.statistics.edges_cut

```

</details>

Nergens in het KDA algoritme wordt een Markov chain opgeslagen door KDA zelf. De Markov chain wordt telkens als argument meegegeven en als return value teruggegeven. Er is een `Statistics` object dat na `_cut_edges` de resultaten opslaat.

**Comment by JoostBerkhout** [comment]
Dank @leonlan voor de inspiratie!
